### ISSUE TITLE
Broken link for ClientPool example

### ISSUE THREAD

**Issue by jeff-mountjoy-stringham** [PragmaticFlow/NBomber.Docs#5]
In the Client Pool page of the documentation (https://github.com/PragmaticFlow/NBomber.Docs/blob/dev/docs/nbomber/client-pool.md?plain=1#L70), the links to full example code are broken. Clicking on the links results in `HTTP 404 - page not found`.

I don't see any example code in https://github.com/PragmaticFlow/NBomber/tree/dev/examples that involves WebSockets, but I did see the MQTT ClientPool example (https://github.com/PragmaticFlow/NBomber/blob/dev/examples/Demo/MQTT/ClientPool/ClientPoolMqttExample.cs). I'm not sure if the link should be removed, or if the example documentation should be updated to showcase the MQTT example instead of WebSockets.

**Comment by AntyaDev** [comment]
Hi @JeffMountjoyStringham-assent ,

Thank you for the info. I will try to add a WebSockets example with ClientPool and publish it. 
I will inform you when it will be ready. Hope today)

**Comment by AntyaDev** [comment]
Hi @JeffMountjoyStringham-assent 
We fixed this doc page: https://nbomber.com/docs/nbomber/client-pool
